### ISSUE TITLE
Cant open log under closed loop fueling

### ISSUE THREAD

**Issue by Sienknecht** [KalebKE/ME7Tuner#14]
Probably an issue on my end... but I cannot seem to open up my log on the closed loop fueling tab but the same log opens up under the open loop fueling tab. Any ideas what I'm doing wrong? 
[closedloop.csv](https://github.com/KalebKE/ME7Tuner/files/8346571/closedloop.csv)

Edit: also, under the configuration I'm not able to set the value for the following; KFMIOP, KFLDRL, KFLDIMX.

**Comment by KalebKE** [comment]
Closed loop operates on a directory that can contain multiple files (since you need lots of data for closed loop). You just want to select the directory the files are in. I have attached a test directory that I know works. Select the 'scaling' folder and it should parse the two files contained within it.

For the configuration, can you provide me with your XDF file? I'll take a look.

[closed_loop_test.zip](https://github.com/KalebKE/ME7Tuner/files/8346672/closed_loop_test.zip)
.

**Comment by KalebKE** [comment]
Closing.

Configurations likely fixed under https://github.com/KalebKE/ME7Tuner/releases/tag/v1.0.3
