### ISSUE TITLE
strange generated values of IOP and IRL 

### ISSUE THREAD

**Issue by taoloo897** [KalebKE/ME7Tuner#23]
Hi.
I tried to generate from my bin and xdf the tables for IOP and IRL.
I put my map sensor max value 4000mbar and desired boost 3000 mbar( 2 bar boost).
The me7tunner generated strange values for IOP last axis value is 276.1 with all cells 73.43 , here i think must be all cells 99
and IRL for last 3 rows with axis values 80 , 90 , 100 all cells had the same values 276.1
[https://www.dropbox.com/s/53f7chkoeopjt02/iop_irl.jpg?dl=0](url)

Thanks and waiting your advice KALEB!

**Comment by KalebKE** [comment]
I would need to see how KFMIOP was generated to determine why the torque request in the upper load columns ended up being the same. Generally it is best to start with the stock KFMIOP.

However, KFMIRL is correct. Based on your maximum boost request and your maximum boost limit (MAP limit) you will only request ~70% of maximum theoretical torque (276 load). So, anything above ~70% torque request in IRL gets limited to your maximum load (276). 

Personally, I would set 'Boost Pressure Maximum' somewhere close to 'MAP Sensor Maximum' (eg, 3800mbar max boost with a 4000mbar MAP limit) and then use LDRXN to request the load (but you may only end up requesting 70% of maximum load). This is how a stock B5 S4 2.7T was calibrated by the OEM. The maximum load is 191, but in reality it only ever requested ~140 load  (about 75% of the theoretical max). As I recall, the RS4 never even quite made it to 191 load, but they extended the range to a 3bar MAP (S4 was a 2.5bar MAP) so it still had bout 75% of the theoretical max.

**Comment by taoloo897** [comment]
Thanks a lot for your explanations.
I have a 4 bar map senzor and i work with 2bar boost. So i put in your application 4000mbar as maximum value of map and 3000mbar as max boost. Aplication suggest me a 276 load limit for 2bar boost what is it correct, and i will request load from ldrxn 276 too. So what i understood is the max torque is lower than max load and never touch on the car more than 70-75% of load, even if i request 99% torque in irl on the columns with axis value 99? Correct?

**Comment by KalebKE** [comment]
Max torque is just a normalized (a range of 0 to 1... or 0% to 100%) function of maximum load. Eg, with a max load of 300 with a torque request of 50% would be 150 load. You are currently capping your maximum load request in IOP to ~70%, so you will never request more than ~270 of load, which is why torque request in IRL above 70% never results in a load request greater than 270.

I would  set your maximum boost much closer to the map limit and use LDRXN to appropriately request ~270 of load (or 70% torque if you want to think about it that way). The OEM calibrators never quested anywhere near 100% torque... it was always closer to a maximum of 75%.

You do not have to tune it like the OEM calibrator... there are a lot of constraints they had that you do not. ME7Tuner exists entirely to give a basis to work from based on how the OEM calibrations were done, but it doesn't mean you have to do it that way or it is the "best" way. But personally, I calibrate my car like the OEM.

**Comment by taoloo897** [comment]
Thanks a lot again. GREATE JOB! I will come back with some results after i 'll try your abordation.
