### ISSUE TITLE
Cant upload logs for closed loop MLHFM

### ISSUE THREAD

**Issue by Streacy1990** [KalebKE/ME7Tuner#3]
Hi,

There seems to be an issue with uploading Me7 logs. It will not recognize/show any values when logs loaded. Is there a set format to which the logs must be uploaded? 

Current format

TimeStamp | fr_w | fra_w | nmot_w | uhfm_w | wdkba | B_lr |  
TIME | LambdaControl | AdaptationPartial | EngineSpeed | MAFSensorVoltage | ThrottlePlateAngle | Lambda Control Active

Simon

**Comment by KalebKE** [comment]
Hi.

The closed loop logs are loaded by directory, not by file. Are you selecting a directory with the closed loop files within it to open?

**Comment by golfputtputt** [comment]
according to your readme doc, under the Closed loop MLHFM header, it only states you need: Timestamp | fr_w | fra_w | nmot_w | uhfm_w | wdkba | B_lr

is this a misnomer or did I miss something?
also, all your images are broken in the readme.

**Comment by KalebKE** [comment]
@golfputtputt 

It the most recent version it needs the following for closed loop. I will update the documentation.

Timestamp | nmot | fr_w | fra_2 | uhfm_w | wdkba | B_lr | rl_w

My webserver has been down and I haven't had a chance to look at it. Hopefully I'll get it (and the images) fixed soon.

**Comment by golfputtputt** [comment]
Thanks kaleb. Unfortunately it seems i’m doing something incorrectly. I tried all of those variables you mentioned in me7Logger and also tried different styles of heading (sans units, sans descriptor, sans me7L header) and i cant seem to get the calculator to show anything. File location is found but nothing plots. MLHFM csv plots fine in the previous function though.

**Comment by KalebKE** [comment]
@golfputtputt

Can you attach your log for me? Just the headers with a few rows of data is sufficient.

**Comment by golfputtputt** [comment]
Here's the log. 
    On Tuesday, July 20, 2021, 11:46:22 AM EDT, KalebKE ***@***.***> wrote:  
 
 


@golfputtputt

Can you attach your log for me? Just the headers with a few rows of data is sufficient.

**Comment by golfputtputt** [comment]
Am i uploading the correct log?

**Comment by KalebKE** [comment]
@golfputtputt 

It doesn't look like your log uploaded. It should look like this.

[closed_loop_20190120_132341.csv](https://github.com/KalebKE/ME7Tuner/files/6872563/closed_loop_20190120_132341.csv)

**Comment by golfputtputt** [comment]
ok thanks. I'm missing a lot of variables. I'll try that out.
    On Saturday, July 24, 2021, 10:16:48 AM EDT, KalebKE ***@***.***> wrote:  
 
 


@golfputtputt

It doesn't look like your log uploaded. It should look like this.

closed_loop_20190120_132341.csv

**Comment by golfputtputt** [comment]
It works. Trying to get it to output data that works properly. So far, the only thing its outputed is an MLHFM map that stalls the car at idle. Works wonderfully off idle, but that zone is off, going to pass more data through the utility until it stops stalling.

I found a glitch. ‘SaveMLHFM’ button exports the raw corrections only without the fit polynomial effects. I couldnt get it to export a file that had polynomial effects applied. Luckily the live table to the right does have the the polynomial applied and i can just copy past that to excel so thats a decent workaround. Just thought you should know.

**Comment by KalebKE** [comment]
@golfputtputt 

I am glad to hear you got it working.

I have fixed the issue with 'Save MLHFM' and it not exporting the fit curve. I have pushed a new release 'v0.3'. 

Dialing idle can be a pain. A few strategies. 

* Preform a throttle body calibration with VAG-COM. The 'ignition-on and wait 30 seconds' trick is not enough.
* Don't start logging until the engine has warmed up enough to open the thermostat 
* Log it at idle for a least a few minutes (say at least 5 minutes). The narrow band O2 is extremely noisy and you need a good amount of data for the averaging to work.
* Find a parking lot where you can just the car idle in gear (1st and 2nd) and creep along with some load
* If this is all failing, reset back to your base curve where it does idle and tune it empirically based on STFT/LTFT/Wideband O2. Then use the 'Configure Filter' and set up the 'Minimum RPM' to say ~800 rpm so it doesn't touch idle and then use the polynomial to smooth. 

I am going to close this issue. Please open new issues as needed.

**Comment by golfputtputt** [comment]
Thank you!!!

I appreciate the responsiveness and update. Wonderful work on this program.

Regarding the log changes: yea a few suggestions on your list crossed my mind and i think i’ll do a fresh pass of data keeping those things in mind. 

Tb adapt vcds will be done for sure. I think a big thing is a uploaded a curve without confirming visual 2d table, discovering too late before i uploaded that it did not export polynomial modded data. Looking at the raw, there was a huge dip in correction around idle region. 

Once again, serious thanks for this open source sw, you’re a saint.

**Comment by golfputtputt** [comment]
Hey, one more issue I've found which has prevented me from proceeding. LDRPID KFLDIMX is cut off without a scroll option and I'm unable to paste the data into it for calculations. 
thanks.

    On Saturday, July 31, 2021, 05:45:38 PM EDT, G Perman ***@***.***> wrote:  
 
 Thank you!!!
I appreciate the responsiveness and update. Wonderful work on this program.
Regarding the log changes: yea a few suggestions on your list crossed my mind and i think i’ll do a fresh pass of data keeping those things in mind. 
Tb adapt vcds will be done for sure. I think a big thing is a uploaded a curve without confirming visual 2d table, discovering too late before i uploaded that it did not export polynomial modded data. Looking at the raw, there was a huge dip in correction around idle region. 
Once again, serious thanks for this open source sw, you’re a saint. 

Sent from my iPhone

On Jul 31, 2021, at 2:32 PM, KalebKE ***@***.***> wrote:



﻿


@golfputtputt

I am glad to hear you got it working.

I have fixed the issue with 'Save MLHFM' and it not exporting the fit curve. I have pushed a new release 'v0.3'.

Dialing idle can be a pain. A few strategies.
   
   - Preform a throttle body calibration with VAG-COM. The 'ignition-on and wait 30 seconds' trick is not enough.
   - Don't start logging until the engine has warmed up enough to open the thermostat
   - Log it at idle for a least a few minutes (say at least 5 minutes). The narrow band O2 is extremely noisy and you need a good amount of data for the averaging to work.
   - Find a parking lot where you can just the car idle in gear (1st and 2nd) and creep along with some load
   - If this is all failing, reset back to your base curve where it does idle and tune it empirically based on STFT/LTFT/Wideband O2. Then use the 'Configure Filter' and set up the 'Minimum RPM' to say ~800 rpm so it doesn't touch idle and then use the polynomial to smooth.

I am going to close this issue. Please open new issues as needed.

**Comment by golfputtputt** [comment]
also, the 3D visual graph buttons dont seem to work.
    On Wednesday, August 25, 2021, 10:31:01 AM EDT, G Perman ***@***.***> wrote:  
 
  
Hey, one more issue I've found which has prevented me from proceeding. LDRPID KFLDIMX is cut off without a scroll option and I'm unable to paste the data into it for calculations. 
thanks.

    On Saturday, July 31, 2021, 05:45:38 PM EDT, G Perman ***@***.***> wrote:  
 
 Thank you!!!
I appreciate the responsiveness and update. Wonderful work on this program.
Regarding the log changes: yea a few suggestions on your list crossed my mind and i think i’ll do a fresh pass of data keeping those things in mind. 
Tb adapt vcds will be done for sure. I think a big thing is a uploaded a curve without confirming visual 2d table, discovering too late before i uploaded that it did not export polynomial modded data. Looking at the raw, there was a huge dip in correction around idle region. 
Once again, serious thanks for this open source sw, you’re a saint. 

Sent from my iPhone

On Jul 31, 2021, at 2:32 PM, KalebKE ***@***.***> wrote:



﻿


@golfputtputt

I am glad to hear you got it working.

I have fixed the issue with 'Save MLHFM' and it not exporting the fit curve. I have pushed a new release 'v0.3'.

Dialing idle can be a pain. A few strategies.
   
   - Preform a throttle body calibration with VAG-COM. The 'ignition-on and wait 30 seconds' trick is not enough.
   - Don't start logging until the engine has warmed up enough to open the thermostat
   - Log it at idle for a least a few minutes (say at least 5 minutes). The narrow band O2 is extremely noisy and you need a good amount of data for the averaging to work.
   - Find a parking lot where you can just the car idle in gear (1st and 2nd) and creep along with some load
   - If this is all failing, reset back to your base curve where it does idle and tune it empirically based on STFT/LTFT/Wideband O2. Then use the 'Configure Filter' and set up the 'Minimum RPM' to say ~800 rpm so it doesn't touch idle and then use the polynomial to smooth.

I am going to close this issue. Please open new issues as needed.

**Comment by golfputtputt** [comment]
Apologies for all the messages.
I solved the prior issue.

Moving on to finishing LDRPID, i logged two files with 4 wot runs each (8 wot runs total). Put logs into one folder, and loaded into ME7tuner. It parsed the files for about 30 minutes before i cancelled it. I’m not sure how long is too long or if i didn't do it correctly. How long does it usually take to parse?

**Comment by KalebKE** [comment]
@golfputtputt 

It can take a few minutes, but it shouldn't take 30 minutes. Can you attach the logs to a comment so I can run them and see what is happening?

**Comment by golfputtputt** [comment]
here are the logs
    On Thursday, September 16, 2021, 09:26:00 PM EDT, KalebKE ***@***.***> wrote:  
 
 


@golfputtputt

It can take a few minutes, but it shouldn't take 30 minutes. Can you attach the logs to a comment so I can run them and see what is happening?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by golfputtputt** [comment]
Just checking in to make sure the log files sent correctly

**Comment by KalebKE** [comment]
@golfputtputt 

No, I don't see the logs. You need to use GitHub (not email if you are using email) and attach files to the comment by dragging and dropping them.

**Comment by golfputtputt** [comment]
[LDRPID-KFLDRL.02.csv](https://github.com/KalebKE/ME7Tuner/files/7189068/LDRPID-KFLDRL.02.csv)
[LDRPID-KFLDRL.01.csv](https://github.com/KalebKE/ME7Tuner/files/7189069/LDRPID-KFLDRL.01.csv)

here are the logs

**Comment by KalebKE** [comment]
@golfputtputt 

I see the issues. I'll push out a fix in the morning.

**Comment by KalebKE** [comment]
@golfputtputt 

A couple of issues. 

Barometric pressure was 'pu_w' instead of 'pus_w'. The latter being the raw sensor value. It probably doesn't make a difference, but that is how I wrote it. I didn't have that documented correctly so I fixed that and then I updated your log headers to 'pus_w' so it will work. I have attached the updated versions.

Then I had some code in there that was hunting for 3rd gear and excluding all other gears... That probably isn't right so I allow all gears now. I have pushed a new v0.5 release with those changes.

On the topic of gears... 1st and 2nd gear aren't going to load the engine enough to properly boost the turbos. The side effect of this is likely going to be over boost in higher gears as the N75 PID increases to get the boost up in lower gears that don't generate enough engine load. That being said, it is probably fine to throw those logs in with a bunch of other logs that use higher gears. I generally throw every log I have into the folder I parse (probably close to 1000 at this point) and let it rely on averages to get some ball park results.

You will also likely have to massage your results a bit since the algorithm sort of guesses what the peak boost is (which can happen very late in the RPM band if you have a big turbo).

Anyway I did get some results that look like a reasonable start from your logs with v0.5 and the header change for the barometric pressure.

[LDRPID-KFLDRL_1.csv](https://github.com/KalebKE/ME7Tuner/files/7190597/LDRPID-KFLDRL_1.csv)

[LDRPID-KFLDRL_0.csv](https://github.com/KalebKE/ME7Tuner/files/7190598/LDRPID-KFLDRL_0.csv)

**Comment by golfputtputt** [comment]
ok cool, thank you. I appreciate it. Yea my plan was a mix of 2nd, 3rd and 4th. have you analyzed SB_GLI's LDRPID tool source code? He claims good results through the GUI without need to edit afterward. maybe some Q2 for overboost. 
    On Saturday, September 18, 2021, 04:39:11 PM EDT, KalebKE ***@***.***> wrote:  
 
 


@golfputtputt

A couple of issues.

Barometric pressure was 'pu_w' instead of 'pus_w'. The latter being the raw sensor value. It probably doesn't make a difference, but that is how I wrote it. I didn't have that documented correctly so I fixed that and then I updated your log headers to 'pus_w' so it will work. I have attached the updated versions.

Then I had some code in there that was hunting for 3rd gear and excluding all other gears... That probably isn't right so I allow all gears now. I have pushed a new v0.5 release with those changes.

On the topic of gears... 1st and 2nd gear aren't going to load the engine enough to properly boost the turbos. The side effect of this is likely going to be over boost in higher gears as the N75 PID increases to get the boost up in lower gears that don't generate enough engine load. That being said, it is probably fine to throw those logs in with a bunch of other logs that use higher gears. I generally throw every log I have into the folder I parse (probably close to 1000 at this point) and let it rely on averages to get some ball park results.

You will also likely have to massage your results a bit since the algorithm sort of guesses what the peak boost is (which can happen very late in the RPM band if you have a big turbo).

Anyway I did get some results that look like a reasonable start from your logs with v0.5 and the header change for the barometric pressure.

LDRPID-KFLDRL_1.csv

LDRPID-KFLDRL_0.csv

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by KalebKE** [comment]
@golfputtputt 

I have looked at SB_GLI's LDRPID.

Fundamentally, you are always going to have to empirically modify the results. Anyone who says differently is either ignorant or hyperbolic. There is no way to know exactly what each column of duty cycle is going to end up correspond to in terms of boost levels. You can average the values, take the peak value, take the mode... whatever. It is still a guess, although and educated one. You will need to make some adjustments based on your configuration to maximize spool, safety and drivability.

There is also a significant amount of data scrubbing that needs to happen. Values must be monotonically increasing for interpolation to work. Outliers need to be filtered. Some sort of smoothing should happen. And while the algorithm accounts for absolute ambient air pressure, it does not account for humidity, intake air temperature, air fuel ratio, ignition advance or the gasoline octane and blend. All of those factors can have an enormous effect on spool and change dynamically and can't be easily account for in an algorithm.

The best thing you can do is just log and process as much data as possible and rely on the averages. Otherwise you might have unexpected results when the seasons change (and air temperature and fuel blends change).

**Comment by golfputtputt** [comment]
Would you say a good order of operations would be: hardware > closed loop fuel and load > open loop fuel and load > cam and ignition timing > boost? 

Or is bouncing around a bit an available alternative?

Ex:
Hardware > closed loop fuel and load > open loop fuel and load > boost > larger injectors > closed and open loop again > boost > cam and ignition timing? 

Do the order of the tabs in your tool have meaning?

Seems to be a lot of perspectives on this in nefmoto. 

> There is also a significant amount of data scrubbing that needs to happen. Values must be monotonically increasing for interpolation to work. Outliers need to be filtered. Some sort of smoothing should happen. And while the algorithm accounts for absolute ambient air pressure, it does not account for humidity, intake air temperature, air fuel ratio, ignition advance or the gasoline octane and blend. All of those factors can have an enormous effect on spool and change dynamically and can't be easily account for in an algorithm.

**Comment by KalebKE** [comment]
@golfputtputt 

The order of the tabs does imply the order you should tune your maps in. You have to nail your fueling and maf scaling first so your load request makes sense to the internal models of ME7. That is by far the most important part. If you don't get this right you will just battle ME7's internal models.

If you plan on advancing your cam timing for spool that should be done before you touch ldrpid. You should be able to figure out where to stop advancing the cam with zero duty cycle on the PID.

The then actually tuning ldrpid and the ignition advance should come last. They are both high dependent on each other and the properties of the ambient air (density, temperature, humidity) and whatever fuel you are using.

You may need to touch KFVPDKSD and WDKUGDN to get your throttle opening enough.

You need to get your boost in the ballpark via KFMIRL, KFLDIMX, and KFLDRL. Then you need to get a ton of logs in different ambient air conditions and get KFTARX, FWFTBRTA and LDIATA. This part is overlooked by almost everyone. You want to pull boost and timing in hot weather and add boost and timing in cold weather. Otherwise you are either unsafe or leaving power on the table.

While you are experimenting with load request (boost) and can also adjust the ignition advance. You need less ignition advance as cylinder pressures increase. So as boost increases you can back off on the ignition advance until you become knock limited and find the place that produces the highest cylinder pressures safely.

Then you can take all of those logs and pump them through the LDRPID to convert over to feed forward PID and fine tune everything exactly the way you want it.

**Comment by golfputtputt** [comment]
Also, having some odd results in the KFMIRL part of the tool. Output is odd and minimum torque dropdown menu makes the graph react 20% of the time or so. IE: It seems to only work sometimes

![Capture KFMIRL](https://user-images.githubusercontent.com/87508839/134363267-dacbfb7f-3619-4bfd-a80f-3cd505535a06.PNG)
es

**Comment by golfputtputt** [comment]
Regarding engine loading in the lower gears. Is the n75 PID exclusively responsible for “pre spooling” the turbo or is there a throttle PID involved related to this? 

I’m having an issue with accel pedal angle remaining steady and the throttle plate opens up then closes seemingly without pilot input control in the 1200-3000rpm range. 
> On the topic of gears... 1st and 2nd gear aren't going to load the engine enough to properly boost the turbos. The side effect of this is likely going to be over boost in higher gears as the N75 PID increases to get the boost up in lower gears that don't generate enough engine load.
